server:
  port: 8585

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://localhost:8484
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8787
          predicates:
            - Path=/api/user/**

        - id: order-service
          uri: http://localhost:8686
          predicates:
            - Path=/api/order/**
