server:
  port: 8787

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

internal:
  jwt:
    secret: INTERNAL_SECRET_KEY_32_CHARS_MIN
